-- MySQL Script generated by MySQL Workbench
-- Thu Jan 16 11:28:27 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Author Dimension`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Author Dimension` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Author Dimension` (
  `ISBN` INT NOT NULL,
  `Student ID` INT NOT NULL,
  `Staff ID` INT NOT NULL,
  `Issue Date` TEXT NOT NULL,
  `Borrow till` INT NULL,
  PRIMARY KEY (`ISBN`, `Student ID`, `Staff ID`, `Issue Date`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Book dimension`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Book dimension` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Book dimension` (
  `ISBN KEY` INT NOT NULL,
  `ISBN` INT NOT NULL,
  `Title` TEXT NOT NULL,
  `Author` TEXT NOT NULL,
  `Edition` INT NULL,
  `Copies` TEXT NULL,
  PRIMARY KEY (`ISBN KEY`, `ISBN`, `Author`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Category Dimension`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Category Dimension` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Category Dimension` (
  `Category Key` INT NOT NULL,
  `Category Key` INT NOT NULL,
  `Category Name` TEXT NOT NULL,
  PRIMARY KEY (`Category Key`, `Category Key`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Literature Fact Table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Literature Fact Table` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Literature Fact Table` (
  `idtable1` INT NOT NULL,
  `Category Key` INT NOT NULL,
  `Publisher Key` INT NOT NULL,
  `ISBN KEY` INT NOT NULL,
  `Present Copies` TEXT NULL,
  `Borrowed Copies` TEXT NULL,
  `Issue date` TEXT NULL,
  `Borrow Till` TEXT NULL,
  PRIMARY KEY (`idtable1`, `Publisher Key`, `Category Key`, `ISBN KEY`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Publisher Dimension`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Publisher Dimension` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Publisher Dimension` (
  `Publisher Key` INT NOT NULL,
  `Publisher Name` INT NOT NULL,
  `Publisher ID` INT NOT NULL,
  PRIMARY KEY (`Publisher Key`, `Publisher ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
